# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy Fullstack app

on:
  pull_request:
    branches:
      - devel
      - stage
      - prod

jobs:
  check-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PRs
        run: |
          if [[ "${{ github.base_ref }}" == "devel" ]]; then
            if [[ ! "${{ github.head_ref }}" =~ ^(feature|bugfix) ]]; then
              echo "Only allow merges into the devel branch from branches feature/bugfix."
              exit 1
            fi
          elif [[ "${{ github.base_ref }}" == "stage" ]]; then
            if [[ "${{ github.head_ref }}" != "devel" ]]; then
              echo "Only allow merges into the stage branch from the devel branch."
              exit 1
            fi
          elif [[ "${{ github.base_ref }}" == "prod" ]]; then
            if [[ "${{ github.head_ref }}" != "stage" ]]; then
              echo "Only allow merges into the prod branch from the stage branch."
              exit 1
            fi
          fi

  build:
    needs: check-merge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "15.x"

      - name: Install dependencies
        run: npm ci

      - name: Linter (ESLint)
        run: npm run lint

      - name: Formatter (Prettier)
        run: npm run lint

      - name: Test (Jest)
        run: CI=true npm run test

      - name: Build npm run build
        run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: nodejs-build
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      - run: cd terraform

      - name: Set ENVIRONMENT
        run: echo "TF_ENV=$(echo ${{ github.head_ref }} )" >> $GITHUB_ENV

      - uses: actions/download-artifact@v4
        with:
          name: nodejs-build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
        run: terraform init

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform create workspace for devel
        run: |
          if [[ ! "${{ env.TF_ENV }}" =~ ^(devel|stage|prod) ]]; then
            if [[ "${{ env.TF_ENV }}" =~ ^(feature) ]]; then
              terraform workspace new devel
              terraform workspace select devel
            else
              terraform workspace new "${{ env.TF_ENV }}" 
              terraform workspace select "${{ env.TF_ENV }}"
            fi
          else
            echo "Only allow deployments from devel| stage | prod "
            exit 0
          fi

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -var env_tf="${{ env.TF_ENV }}"
